title: Head In The Clouds
email: jamesrcounts@outlook.com
description: >
  I'm Jim Counts, an independent consultant specializing in legacy code, cloud, and DevOps.  This blog is where I'll share my thoughts and tips on cloud and serverless computing.
baseurl: ""
url: ""
twitter_username: jamesrcounts
github_username:  jamesrcounts

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - circle.yml
