title: Cloud as Code
email: jamesrcounts@outlook.com
description: >
  I'm Jim Counts. DevOps & cloud engineer. Writing about Azure, Terraform, CI/CD, and secure infra. Automating all the things so you can ship faster (and sleep better).
baseurl: ""
url: ""
github_username:  jamesrcounts
linkedin_username: jamesrcounts

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-responsive-image

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - circle.yml

responsive_image:
  template: _includes/srcset.html
  cache: false
  sizes:
    - width: 320
    - width: 480
    - width: 740
    - width: 960
    - width: 1480
