title: Cloud as Code
email: jamesrcounts@outlook.com
description: >
  I'm Jim Counts, an independent consultant specializing in legacy code, cloud, and DevOps.  This blog is where I'll share my thoughts and tips on cloud infrastructure and automation.
baseurl: ""
url: ""
twitter_username: jamesrcounts
github_username:  jamesrcounts

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-responsive-image

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - circle.yml

responsive_image:
  template: _includes/srcset.html
  cache: false
  sizes:
    - width: 320
    - width: 480
    - width: 740