version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node

    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - jekyll-bundle-{{ checksum "Gemfile.lock" }}
            - jekyll-bundle-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: jekyll-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Jekyll Build
          command: bundle exec jekyll build

      - run:
          name: Jekyll Proof
          command: bundle exec htmlproofer ./_site --check-html --disable-external

      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - ./_site

  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .

      - awscli/install
      
      - run:
          name: Deploy to S3
          command: aws s3 sync ./_site s3://jamesrcounts.com/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
