version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node

    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

# dependencies:
#   post:
#     - bundle exec jekyll build

# test:
#   post:
#     - bundle exec htmlproofer ./_site --check-html --disable-external

# deployment:
#   prod:
#     branch: master
#     commands:
#       - aws s3 sync ./_site s3://jamesrcounts.com/ --delete