version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node

    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - jekyll-bundle-{{ checksum "Gemfile.lock" }}
            - jekyll-bundle-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: jekyll-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Jekyll Build
          command: bundle exec jekyll build

      - run:
          name: Jekyll Proof
          command: bundle exec htmlproofer ./_site --check-html --disable-external

# deployment:
#   prod:
#     branch: master
#     commands:
#       - aws s3 sync ./_site s3://jamesrcounts.com/ --delete