name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Show bundler version
        run: bundle -v

      - name: Cache Ruby bundle
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: jekyll-bundle-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            jekyll-bundle-

      - name: Bundle install
        run: bundle check --path vendor/bundle || bundle install --deployment

      - name: Jekyll build
        run: bundle exec jekyll build

      - name: HTMLProofer check
        run: bundle exec htmlproofer ./_site --check-html --disable-external

      - name: Upload _site
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Download _site artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync to S3
        run: aws s3 sync ./_site s3://jamesrcounts.com/ --delete
